### ISSUE TITLE
Cannot run simulator

### ISSUE THREAD

**Issue by wuben2602** [ictr/covid19-outbreak-simulator#12]
* COVID-19 Outbreak Simulator version: latest
* Python version: 3.8.3
* Operating System: Windows 10

### Description
The outbreak simulator cannot complete the simulation
I think maybe because i didn't install the requirements.txt but everytime I try to run `pip install -r requirements.txt`, it can't find the file or directory.

### What I Did
conda create -n covid19simtest
conda activate covid19simtest
pip install numpy,scipy
pip install covid19-outbreak-simulator
cd covid19-outbreak-simulator 
(covid19simtest) [u235123@soshub covid19-outbreak-simulator]$ outbreak_simulator --popsize A=2000 B=500 --rep 10 --handle-symptomatic quarantine_14 1   --susceptibility A=1.2 --symptomatic-r0 A=1.2 B=0.8 --logfile hetero.log   --stop-if 't>40'   --plugin stat --interval 1   --plugin insert A=5 --prop-of-infected 0.5 --interval 1   | python contrib/report2csv.py > hetero.csv

Error Message:
`
Traceback (most recent call last):
  File "contrib/report2csv.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/home/bwu/.conda/envs/covid19simtest/lib/python3.8/site-packages/covid19_outbreak_simulator/simulator.py", line 36, in load_plugins
    obj = getattr(mod, plugin_name)(simulator)
AttributeError: module 'stat' has no attribute 'stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bwu/.conda/envs/covid19simtest/bin/outbreak_simulator", line 8, in <module>
    sys.exit(main())
  File "/home/bwu/.conda/envs/covid19simtest/lib/python3.8/site-packages/covid19_outbreak_simulator/cli.py", line 175, in main
    load_plugins(args.plugin)
  File "/home/bwu/.conda/envs/covid19simtest/lib/python3.8/site-packages/covid19_outbreak_simulator/simulator.py", line 38, in load_plugins
    raise ValueError(
ValueError: Failed to retrieve plugin stat from module stat: module 'stat' has no attribute 'stat'
(covid19simtest) [u235123@soshub covid19-outbreak-simulator]$
`

**Comment by BoPeng** [comment]
This is perhaps because 

```
pip install covid19-outbreak-simulator
```
installs the last released version, which does not have `plugins/stat`. Please try

```
pip install -e .
```
to install from the source directory and try again.

**Comment by wuben2602** [comment]
That solves my problem. Thank you!
